project:
  type: website

website:
  title: "LAB6"
  navbar:
    left:
      - href: about.qmd
        text: ABOUT
      - href: Lab6_Work_with_Models.qmd
        text: LAB6 WORK WITH MODELS


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    code-fold: true
    code-overflow: wrap
    
execute: 
  echo: true
  warning: false
